
name = "DashShare"
uuid = "1b08a953-4be3-4667-9a23-0f78dab5d0a9"
authors = ["Colin Brust <colin.brust@mso.umt.edu>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
